CREATE TABLE "EMP" (
	"EMP_ID"	CHAR(6)		NOT NULL,
	"DEPT_ID"	CHAR(6)		NOT NULL,
	"PS_ID"	CHAR(6)		NOT NULL,
	"ROLE_ID"	CHAR(6)		NULL,
	"CN_ID"	CHAR(6)		NULL,
	"EMP_IMG"	VARCHAR2(100)		NULL,
	"EMP_NAME"	VARCHAR2(30)		NOT NULL,
	"EMP_AGE"	NUMBER(3)		NOT NULL,
	"EMP_GEN"	CHAR(1)		NOT NULL,
	"EMP_PASS"	VARCHAR2(8)		NULL,
	"EMP_RRNO"	VARCHAR2(14)		NOT NULL,
	"EMP_PHONE"	VARCHAR2(13)		NOT NULL,
	"EMP_TEL"	VARCHAR2(13)		NULL,
	"EMP_ZIP"	CHAR(6)		NOT NULL,
	"EMP_ADDR"	VARCHAR2(200)		NOT NULL,
	"EMP_MAIL"	VARCHAR2(30)		NOT NULL,
	"EMP_CMP_YMD"	TIMESTAMP		NOT NULL,
	"EMP_CAREER"	NUMBER(5)		NOT NULL,
	"EMP_QUIT_DT"	TIMESTAMP		NULL,
	"EMP_LIMIT_YN"	CHAR(1)		NULL
);

COMMENT ON COLUMN "EMP"."EMP_ID" IS '사원ID';

COMMENT ON COLUMN "EMP"."DEPT_ID" IS '부서ID';

COMMENT ON COLUMN "EMP"."PS_ID" IS '직급ID';

COMMENT ON COLUMN "EMP"."ROLE_ID" IS '역할 ID';

COMMENT ON COLUMN "EMP"."CN_ID" IS '접속상태ID';

COMMENT ON COLUMN "EMP"."EMP_IMG" IS '프로필사진';

COMMENT ON COLUMN "EMP"."EMP_NAME" IS '이름';

COMMENT ON COLUMN "EMP"."EMP_AGE" IS '나이';

COMMENT ON COLUMN "EMP"."EMP_GEN" IS '성별';

COMMENT ON COLUMN "EMP"."EMP_PASS" IS '비밀번호';

COMMENT ON COLUMN "EMP"."EMP_RRNO" IS '주민등록번호';

COMMENT ON COLUMN "EMP"."EMP_PHONE" IS '휴대번호';

COMMENT ON COLUMN "EMP"."EMP_TEL" IS '전화번호';

COMMENT ON COLUMN "EMP"."EMP_ZIP" IS '우편번호';

COMMENT ON COLUMN "EMP"."EMP_ADDR" IS '주소';

COMMENT ON COLUMN "EMP"."EMP_MAIL" IS '이메일';

COMMENT ON COLUMN "EMP"."EMP_CMP_YMD" IS '입사일';

COMMENT ON COLUMN "EMP"."EMP_CAREER" IS '경력';

COMMENT ON COLUMN "EMP"."EMP_QUIT_DT" IS '퇴사일';

COMMENT ON COLUMN "EMP"."EMP_LIMIT_YN" IS '제한여부';

CREATE TABLE "ROLE" (
	"ROLE_ID"	CHAR(6)		NOT NULL,
	"ROLE_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ROLE"."ROLE_ID" IS '역할ID';

COMMENT ON COLUMN "ROLE"."ROLE_NAME" IS '역할 명';

CREATE TABLE "BOOKMARK_BOARD" (
	"BB_ID"	CHAR(6)		NOT NULL,
	"BP_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL,
	"BB_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BB_DEL_DT"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "BOOKMARK_BOARD"."BB_ID" IS '사내게시판즐겨찾기ID';

COMMENT ON COLUMN "BOOKMARK_BOARD"."BP_ID" IS '사내게시판 게시글ID';

COMMENT ON COLUMN "BOOKMARK_BOARD"."EMP_ID" IS '사원ID';

COMMENT ON COLUMN "BOOKMARK_BOARD"."BB_REG_DT" IS '사내게시판즐겨찾기 등록일';

COMMENT ON COLUMN "BOOKMARK_BOARD"."BB_DEL_DT" IS '사내게시판즐겨찾기 취소일';

CREATE TABLE "PROJECT" (
	"PRO_ID"	CHAR(6)		NOT NULL,
	"PRO_ST_ID"	CHAR(6)		NOT NULL,
	"PRO_NAME"	VARCHAR2(100)		NOT NULL,
	"PRO_DESC"	CLOB		NULL,
	"PRO_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"PRO_DDLINE_EX"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"PRO_DDLINE_DT"	TIMESTAMP		NULL,
	"PRO_DDLINE_YN"	CHAR(1)		NULL,
	"PRO_DEL_YN"	CHAR(1)		NULL
);

COMMENT ON COLUMN "PROJECT"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "PROJECT"."PRO_ST_ID" IS '프로젝트 상태ID';

COMMENT ON COLUMN "PROJECT"."PRO_NAME" IS '프로젝트명';

COMMENT ON COLUMN "PROJECT"."PRO_DESC" IS '프로젝트 설명';

COMMENT ON COLUMN "PROJECT"."PRO_REG_DT" IS '프로젝트 등록일';

COMMENT ON COLUMN "PROJECT"."PRO_DDLINE_EX" IS '프로젝트 마감예정일';

COMMENT ON COLUMN "PROJECT"."PRO_DDLINE_DT" IS '프로젝트 마감일';

COMMENT ON COLUMN "PROJECT"."PRO_DDLINE_YN" IS '프로젝트 마감여부상태코드';

COMMENT ON COLUMN "PROJECT"."PRO_DEL_YN" IS '프로젝트 삭제여부상태코드';

CREATE TABLE "ISSUE" (
	"ISSUE_ID"	CHAR(6)		NOT NULL,
	"PRO_ID"	CHAR(6)		NOT NULL,
	"ISSUE_REG_ID"	CHAR(6)		NOT NULL,
	"IMPRT_ID"	CHAR(6)		NOT NULL,
	"CLSFC_ID"	CHAR(6)		NOT NULL,
	"ISSUE_TITLE"	VARCHAR2(100)		NOT NULL,
	"ISSUE_CN"	CLOB		NOT NULL,
	"ISSUE_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"ISSUE_MOD_DT"	TIMESTAMP		NULL,
	"ISSUE_DEL_DT"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "ISSUE"."ISSUE_ID" IS '이슈ID';

COMMENT ON COLUMN "ISSUE"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "ISSUE"."ISSUE_REG_ID" IS '이슈 작성자';

COMMENT ON COLUMN "ISSUE"."IMPRT_ID" IS '이슈 중요도ID';

COMMENT ON COLUMN "ISSUE"."CLSFC_ID" IS '이슈 분류 ID';

COMMENT ON COLUMN "ISSUE"."ISSUE_TITLE" IS '이슈 제목';

COMMENT ON COLUMN "ISSUE"."ISSUE_CN" IS '이슈 내용';

COMMENT ON COLUMN "ISSUE"."ISSUE_REG_DT" IS '이슈 등록일';

COMMENT ON COLUMN "ISSUE"."ISSUE_MOD_DT" IS '이슈 수정일';

COMMENT ON COLUMN "ISSUE"."ISSUE_DEL_DT" IS '이슈 삭제일';

CREATE TABLE "FILE_SAVE_FILE" (
	"FSF_ID"	CHAR(6)		NOT NULL,
	"FSN_ID"	CHAR(6)		NOT NULL,
	"PRO_ID"	CHAR(6)		NOT NULL,
	"FSF_REG_ID"	CHAR(6)		NOT NULL,
	"FSF_GB_ID"	CHAR(6)		NOT NULL,
	"FSF_ATTCH_FILE"	VARCHAR2(200)		NOT NULL,
	"FSF_ORG_NM"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "FILE_SAVE_FILE"."FSF_ID" IS '파일저장소 파일ID';

COMMENT ON COLUMN "FILE_SAVE_FILE"."FSN_ID" IS '파일게시글ID';

COMMENT ON COLUMN "FILE_SAVE_FILE"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "FILE_SAVE_FILE"."FSF_REG_ID" IS '사원ID';

COMMENT ON COLUMN "FILE_SAVE_FILE"."FSF_GB_ID" IS '파일저장소 파일구분ID';

COMMENT ON COLUMN "FILE_SAVE_FILE"."FSF_ATTCH_FILE" IS '파일저장소 첨부파일';

COMMENT ON COLUMN "FILE_SAVE_FILE"."FSF_ORG_NM" IS '파일저장소 원본파일명';

CREATE TABLE "ISSUE_FILE" (
	"ISSFF_ID"	CHAR(6)		NOT NULL,
	"ISSUE_ID"	CHAR(6)		NOT NULL,
	"PRO_ID"	CHAR(6)		NOT NULL,
	"ISSF_REG_ID"	CHAR(6)		NOT NULL,
	"ISSF_GB_ID"	CHAR(6)		NOT NULL,
	"ISSF_ATTCH_FILE"	VARCHAR2(200)		NOT NULL,
	"ISSF_ORG_NM"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "ISSUE_FILE"."ISSFF_ID" IS '이슈파일ID';

COMMENT ON COLUMN "ISSUE_FILE"."ISSUE_ID" IS '이슈ID';

COMMENT ON COLUMN "ISSUE_FILE"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "ISSUE_FILE"."ISSF_REG_ID" IS '이슈파일 작성자';

COMMENT ON COLUMN "ISSUE_FILE"."ISSF_GB_ID" IS '이슈파일구분ID';

COMMENT ON COLUMN "ISSUE_FILE"."ISSF_ATTCH_FILE" IS '이슈파일 첨부파일';

COMMENT ON COLUMN "ISSUE_FILE"."ISSF_ORG_NM" IS '이슈파일 원본파일명';

CREATE TABLE "FILE_SAVE_NOTICE" (
	"FSN_ID"	CHAR(6)		NOT NULL,
	"FS_ID"	CHAR(6)		NOT NULL,
	"PRO_ID"	CHAR(6)		NOT NULL,
	"FSN_REG_ID"	CHAR(6)		NOT NULL,
	"FSN_TITLE"	VARCHAR2(100)		NOT NULL,
	"FSN_CN"	CLOB		NOT NULL,
	"FSN_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"FSN_MOD_DT"	TIMESTAMP		NULL,
	"FSN_DEL_DT"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "FILE_SAVE_NOTICE"."FSN_ID" IS '프로젝트 파일저장소 게시글ID';

COMMENT ON COLUMN "FILE_SAVE_NOTICE"."FS_ID" IS '파일저장소ID';

COMMENT ON COLUMN "FILE_SAVE_NOTICE"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "FILE_SAVE_NOTICE"."FSN_REG_ID" IS '프로젝트 파일저장소 게시글 작성자';

COMMENT ON COLUMN "FILE_SAVE_NOTICE"."FSN_TITLE" IS '프로젝트 파일저장소 게시글 제목';

COMMENT ON COLUMN "FILE_SAVE_NOTICE"."FSN_CN" IS '프로젝트 파일저장소 게시글 내용';

COMMENT ON COLUMN "FILE_SAVE_NOTICE"."FSN_REG_DT" IS '프로젝트 파일저장소 게시글 등록일';

COMMENT ON COLUMN "FILE_SAVE_NOTICE"."FSN_MOD_DT" IS '프로젝트 파일저장소 게시글 수정일';

COMMENT ON COLUMN "FILE_SAVE_NOTICE"."FSN_DEL_DT" IS '프로젝트 파일저장소 게시글 삭제일';

CREATE TABLE "TASK" (
	"TASK_ID"	CHAR(6)		NOT NULL,
	"TS_ID"	CHAR(6)		NOT NULL,
	"PRO_ID"	CHAR(6)		NULL,
	"TASK_MAN_ID"	CHAR(6)		NULL,
	"TASK_TOP_ID"	CHAR(6)		NULL,
	"TPS_ID"	CHAR(6)		NOT NULL,
	"TASK_REG_ID"	CHAR(6)		NULL,
	"TASK_TITLE"	VARCHAR2(100)		NOT NULL,
	"TASK_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"TASK_DDLINE_DT"	TIMESTAMP		NULL,
	"TASK_MOD_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NULL,
	"TASK_CN"	CLOB		NOT NULL,
	"TASK_RQRD"	NUMBER(5)		NOT NULL,
	"TASK_EST_TIME"	NUMBER(5)		NOT NULL,
	"TASK_COMP_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NULL,
	"TASK_DEL_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NULL
);

COMMENT ON COLUMN "TASK"."TASK_ID" IS '일감ID';

COMMENT ON COLUMN "TASK"."TS_ID" IS '일감상태ID';

COMMENT ON COLUMN "TASK"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "TASK"."TASK_MAN_ID" IS '담당자';

COMMENT ON COLUMN "TASK"."TASK_TOP_ID" IS '상위일감';

COMMENT ON COLUMN "TASK"."TPS_ID" IS '일감처리ID';

COMMENT ON COLUMN "TASK"."TASK_REG_ID" IS '일감 등록자ID';

COMMENT ON COLUMN "TASK"."TASK_TITLE" IS '일감 제목';

COMMENT ON COLUMN "TASK"."TASK_REG_DT" IS '일감 등록일';

COMMENT ON COLUMN "TASK"."TASK_DDLINE_DT" IS '일감 마감일';

COMMENT ON COLUMN "TASK"."TASK_MOD_DT" IS '일감 수정일';

COMMENT ON COLUMN "TASK"."TASK_CN" IS '일감 내용';

COMMENT ON COLUMN "TASK"."TASK_RQRD" IS '일감 소요시간';

COMMENT ON COLUMN "TASK"."TASK_EST_TIME" IS '일감 예상시간';

COMMENT ON COLUMN "TASK"."TASK_COMP_DT" IS '일감 처리완료일';

COMMENT ON COLUMN "TASK"."TASK_DEL_DT" IS '일감 삭제일';

CREATE TABLE "TASK_FILE" (
	"TF_ID"	CHAR(6)		NOT NULL,
	"TASK_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL,
	"TF_ATTCH_FILE"	VARCHAR2(200)		NOT NULL,
	"TF_ORG_NM"	VARCHAR2(100)		NOT NULL,
	"TF_GB_ID"	CHAR(6)		NOT NULL
);

COMMENT ON COLUMN "TASK_FILE"."TF_ID" IS '일감파일ID';

COMMENT ON COLUMN "TASK_FILE"."TASK_ID" IS '일감ID';

COMMENT ON COLUMN "TASK_FILE"."EMP_ID" IS '사원ID';

COMMENT ON COLUMN "TASK_FILE"."TF_ATTCH_FILE" IS '일감 첨부파일';

COMMENT ON COLUMN "TASK_FILE"."TF_ORG_NM" IS '일감 원본파일명';

COMMENT ON COLUMN "TASK_FILE"."TF_GB_ID" IS '일감파일구분ID';

CREATE TABLE "TASK_PEP" (
	"TP_ID"	CHAR(6)		NOT NULL,
	"TASK_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL
);

COMMENT ON COLUMN "TASK_PEP"."TP_ID" IS '작업내역ID';

COMMENT ON COLUMN "TASK_PEP"."TASK_ID" IS '일감ID';

COMMENT ON COLUMN "TASK_PEP"."EMP_ID" IS '작업자ID';

CREATE TABLE "TODAY_LIST" (
	"TL_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"TL_IDX"	NUMBER(3)		NOT NULL,
	"TASK_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL
);

COMMENT ON COLUMN "TODAY_LIST"."TL_REG_DT" IS '오늘의일정 등록일';

COMMENT ON COLUMN "TODAY_LIST"."TL_IDX" IS '오늘의일정 순번';

COMMENT ON COLUMN "TODAY_LIST"."TASK_ID" IS '일감ID';

COMMENT ON COLUMN "TODAY_LIST"."EMP_ID" IS '사원ID';

CREATE TABLE "BOARD_POST" (
	"BP_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL,
	"BP_MOD_ID"	CHAR(6)		NULL,
	"BRD_ID"	CHAR(6)		NOT NULL,
	"BP_TITLE"	VARCHAR2(100)		NOT NULL,
	"BP_CN"	CLOB		NOT NULL,
	"BP_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BP_DEL_DT"	TIMESTAMP		NULL,
	"BP_OP_YN"	CHAR(1)		NULL,
	"BP_CNT"	NUMBER(10)		NOT NULL,
	"BP_MOD_DT"	TIMESTAMP		NULL,
	"BP_SHR_YN"	CHAR(1)		NULL,
	"BP_NTC_ID"	CHAR(6)		NULL
);

COMMENT ON COLUMN "BOARD_POST"."BP_ID" IS '사내게시판 게시글ID';

COMMENT ON COLUMN "BOARD_POST"."EMP_ID" IS '사내게시판 게시글 작성자';

COMMENT ON COLUMN "BOARD_POST"."BP_MOD_ID" IS '사내게시판 게시글 수정자';

COMMENT ON COLUMN "BOARD_POST"."BRD_ID" IS '사내게시판ID';

COMMENT ON COLUMN "BOARD_POST"."BP_TITLE" IS '사내게시판 제목';

COMMENT ON COLUMN "BOARD_POST"."BP_CN" IS '사내게시판 내용';

COMMENT ON COLUMN "BOARD_POST"."BP_REG_DT" IS '사내게시판 게시글 등록일';

COMMENT ON COLUMN "BOARD_POST"."BP_DEL_DT" IS '사내게시판 게시글 삭제일';

COMMENT ON COLUMN "BOARD_POST"."BP_OP_YN" IS '사내게시판 게시글 공개여부';

COMMENT ON COLUMN "BOARD_POST"."BP_CNT" IS '사내게시판 게시글 조회수';

COMMENT ON COLUMN "BOARD_POST"."BP_MOD_DT" IS '사내게시판 게시글 수정일';

COMMENT ON COLUMN "BOARD_POST"."BP_SHR_YN" IS '나눔상태코드';

COMMENT ON COLUMN "BOARD_POST"."BP_NTC_ID" IS '공지용 사내게시판ID';

CREATE TABLE "BOAD_POST_FILE" (
	"BP_FILE_ID"	CHAR(6)		NOT NULL,
	"BP_ID"	CHAR(6)		NOT NULL,
	"BP_FILE_GB_ID"	CHAR(6)		NOT NULL,
	"BP_ATTCH_FILE"	VARCHAR2(200)		NOT NULL,
	"BP_ORG_NM"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "BOAD_POST_FILE"."BP_FILE_ID" IS '사내게시판 파일ID';

COMMENT ON COLUMN "BOAD_POST_FILE"."BP_ID" IS '사내게시판 게시글ID';

COMMENT ON COLUMN "BOAD_POST_FILE"."BP_FILE_GB_ID" IS '사내게시판 게시글 파일구분ID';

COMMENT ON COLUMN "BOAD_POST_FILE"."BP_ATTCH_FILE" IS '사내게시판 게시글 첨부파일';

COMMENT ON COLUMN "BOAD_POST_FILE"."BP_ORG_NM" IS '사내게시판 게시글 원본파일명';

CREATE TABLE "LIKEE" (
	"EMP_ID"	CHAR(6)		NOT NULL,
	"BP_ID"	CHAR(6)		NOT NULL,
	"LIKE_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"LIKE_YN"	CHAR(1)		NULL
);

COMMENT ON COLUMN "LIKEE"."EMP_ID" IS '사원ID';

COMMENT ON COLUMN "LIKEE"."BP_ID" IS '사내게시판 게시글ID';

COMMENT ON COLUMN "LIKEE"."LIKE_REG_DT" IS '좋아요 등록일';

COMMENT ON COLUMN "LIKEE"."LIKE_YN" IS '좋아요여부';

CREATE TABLE "WIKI" (
	"WIKI_ID"	CHAR(6)		NOT NULL,
	"PRO_ID"	CHAR(6)		NOT NULL,
	"WIKI_TITLE"	VARCHAR2(100)		NOT NULL,
	"WIKI_CN"	CLOB		NOT NULL,
	"WIKI_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"WIKI_MOD_DT"	TIMESTAMP		NULL,
	"WIKI_DEL_DT"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "WIKI"."WIKI_ID" IS '위키ID';

COMMENT ON COLUMN "WIKI"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "WIKI"."WIKI_TITLE" IS '위키 제목';

COMMENT ON COLUMN "WIKI"."WIKI_CN" IS '위키 내용';

COMMENT ON COLUMN "WIKI"."WIKI_REG_DT" IS '위키 등록일';

COMMENT ON COLUMN "WIKI"."WIKI_MOD_DT" IS '위키 수정일';

COMMENT ON COLUMN "WIKI"."WIKI_DEL_DT" IS '위키 삭제일';

CREATE TABLE "WIKI_FILE" (
	"WF_ID"	CHAR(6)		NOT NULL,
	"WIKI_ID"	CHAR(6)		NOT NULL,
	"WK_FILE_GB_ID"	CHAR(6)		NOT NULL,
	"WF_ATTCH_FILE"	VARCHAR2(200)		NOT NULL,
	"WF_ORG_NM"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "WIKI_FILE"."WF_ID" IS '위키파일ID';

COMMENT ON COLUMN "WIKI_FILE"."WIKI_ID" IS '위키ID';

COMMENT ON COLUMN "WIKI_FILE"."WK_FILE_GB_ID" IS '위키 파일구분ID';

COMMENT ON COLUMN "WIKI_FILE"."WF_ATTCH_FILE" IS '위키 첨부파일';

COMMENT ON COLUMN "WIKI_FILE"."WF_ORG_NM" IS '위키 원본파일명';

CREATE TABLE "ISSUE_COMMENT" (
	"IC_ID"	CHAR(6)		NOT NULL,
	"IC_TOP_ID"	CHAR(6)		NULL,
	"PRO_ID"	CHAR(6)		NOT NULL,
	"IC_REG_ID"	CHAR(6)		NOT NULL,
	"ISSUE_ID"	CHAR(6)		NOT NULL,
	"IC_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"IC_MOD_DT"	TIMESTAMP		NULL,
	"IC_CN"	CLOB		NOT NULL,
	"IC_DEL_YN"	CHAR(1)		NULL
);

COMMENT ON COLUMN "ISSUE_COMMENT"."IC_ID" IS '이슈 댓글ID';

COMMENT ON COLUMN "ISSUE_COMMENT"."IC_TOP_ID" IS '상위댓글ID';

COMMENT ON COLUMN "ISSUE_COMMENT"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "ISSUE_COMMENT"."IC_REG_ID" IS '이슈 댓글 작성자';

COMMENT ON COLUMN "ISSUE_COMMENT"."ISSUE_ID" IS '이슈ID';

COMMENT ON COLUMN "ISSUE_COMMENT"."IC_REG_DT" IS '이슈 댓글 작성일';

COMMENT ON COLUMN "ISSUE_COMMENT"."IC_MOD_DT" IS '이슈 댓글 수정일';

COMMENT ON COLUMN "ISSUE_COMMENT"."IC_CN" IS '이슈 댓글 내용';

COMMENT ON COLUMN "ISSUE_COMMENT"."IC_DEL_YN" IS '이슈 댓글 삭제여부상태코드';

CREATE TABLE "DEPT" (
	"DEPT_ID"	CHAR(6)		NOT NULL,
	"DEPT_NAME"	VARCHAR2(60)		NOT NULL,
	"DEPT_YN"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "DEPT"."DEPT_ID" IS '부서ID';

COMMENT ON COLUMN "DEPT"."DEPT_NAME" IS '부서명';

COMMENT ON COLUMN "DEPT"."DEPT_YN" IS '부서 사용여부';

CREATE TABLE "BOARD_COMMENT" (
	"BC_ID"	CHAR(6)		NOT NULL,
	"BC_TOP_ID"	CHAR(6)		NULL,
	"BP_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL,
	"BC_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BC_MOD_DT"	TIMESTAMP		NULL,
	"BC_CN"	CLOB		NOT NULL,
	"BC_DEL_YN"	CHAR(1)		NULL
);

COMMENT ON COLUMN "BOARD_COMMENT"."BC_ID" IS '사내게시판 게시글 댓글ID';

COMMENT ON COLUMN "BOARD_COMMENT"."BC_TOP_ID" IS '사내게시판 게시글 상위댓글ID';

COMMENT ON COLUMN "BOARD_COMMENT"."BP_ID" IS '사내게시판 게시글ID';

COMMENT ON COLUMN "BOARD_COMMENT"."EMP_ID" IS '사내게시판 게시글 작성자';

COMMENT ON COLUMN "BOARD_COMMENT"."BC_REG_DT" IS '사내게시판 게시글 댓글 작성일';

COMMENT ON COLUMN "BOARD_COMMENT"."BC_MOD_DT" IS '사내게시판 게시글 댓글 수정일';

COMMENT ON COLUMN "BOARD_COMMENT"."BC_CN" IS '사내게시판 게시글 댓글 내용';

COMMENT ON COLUMN "BOARD_COMMENT"."BC_DEL_YN" IS '사내게시판 게시글 댓글 삭제여부상태코드';

CREATE TABLE "ALARM" (
	"ALARM_ID"	CHAR(6)		NOT NULL,
	"ALTYPE_ID"	CHAR(6)		NOT NULL,
	"AL_RCVR_ID"	CHAR(6)		NOT NULL,
	"AL_SNDR_IDSEND_USER"	CHAR(6)		NOT NULL,
	"AL_RD_YN"	CHAR(1)		NULL,
	"AL_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"AL_MOVE_URL"	VARCHAR2(200)		NOT NULL,
	"AL_CN"	CLOB		NULL,
	"AL_DEL_YN"	CHAR(1)		NULL
);

COMMENT ON COLUMN "ALARM"."ALARM_ID" IS '알림ID';

COMMENT ON COLUMN "ALARM"."ALTYPE_ID" IS '알림타입ID';

COMMENT ON COLUMN "ALARM"."AL_RCVR_ID" IS '알림 수신자';

COMMENT ON COLUMN "ALARM"."AL_SNDR_IDSEND_USER" IS '알림 송신자';

COMMENT ON COLUMN "ALARM"."AL_RD_YN" IS '알림 읽기여부';

COMMENT ON COLUMN "ALARM"."AL_REG_DT" IS '알림 등록일';

COMMENT ON COLUMN "ALARM"."AL_MOVE_URL" IS '알림 이동URL';

COMMENT ON COLUMN "ALARM"."AL_CN" IS '알림 내용';

COMMENT ON COLUMN "ALARM"."AL_DEL_YN" IS '알림 삭제여부상태코드';

CREATE TABLE "ALARM_TYPE" (
	"ALTYPE_ID"	CHAR(6)		NOT NULL,
	"ALTYPE_NAME"	VARCHAR2(30)		NOT NULL,
	"ALTYPE_CN"	CLOB		NOT NULL
);

COMMENT ON COLUMN "ALARM_TYPE"."ALTYPE_ID" IS '알림타입ID';

COMMENT ON COLUMN "ALARM_TYPE"."ALTYPE_NAME" IS '알림타입명';

COMMENT ON COLUMN "ALARM_TYPE"."ALTYPE_CN" IS '알림 기본내용';

CREATE TABLE "TEAM" (
	"PRO_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL,
	"ROLE_ID"	CHAR(8)		NOT NULL,
	"TEAM_YN"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "TEAM"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "TEAM"."EMP_ID" IS '사원ID';

COMMENT ON COLUMN "TEAM"."ROLE_ID" IS '역할_ID';

COMMENT ON COLUMN "TEAM"."TEAM_YN" IS '승인여부';

CREATE TABLE "TASK_STATUS" (
	"TS_ID"	CHAR(6)		NOT NULL,
	"TS_NAME"	CHAR(6)		NOT NULL
);

COMMENT ON COLUMN "TASK_STATUS"."TS_ID" IS '일감상태ID';

COMMENT ON COLUMN "TASK_STATUS"."TS_NAME" IS '일감상태명';

CREATE TABLE "BOOKMARK_ISSUE" (
	"BI_ID"	CHAR(6)		NOT NULL,
	"ISSUE_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL,
	"PRO_ID"	CHAR(6)		NOT NULL,
	"BI_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BI_DEL_DT"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "BOOKMARK_ISSUE"."BI_ID" IS '이슈 즐겨찾기ID';

COMMENT ON COLUMN "BOOKMARK_ISSUE"."ISSUE_ID" IS '이슈ID';

COMMENT ON COLUMN "BOOKMARK_ISSUE"."EMP_ID" IS '사원ID';

COMMENT ON COLUMN "BOOKMARK_ISSUE"."PRO_ID" IS '프로젝트ID';

COMMENT ON COLUMN "BOOKMARK_ISSUE"."BI_REG_DT" IS '이슈 즐겨찾기 등록일';

COMMENT ON COLUMN "BOOKMARK_ISSUE"."BI_DEL_DT" IS '이슈 즐겨찾기 취소일';

CREATE TABLE "FILE_SAVE" (
	"FS_ID"	CHAR(6)		NOT NULL,
	"PRO_ID"	CHAR(6)		NOT NULL
);

COMMENT ON COLUMN "FILE_SAVE"."FS_ID" IS '파일저장소ID';

COMMENT ON COLUMN "FILE_SAVE"."PRO_ID" IS '프로젝트ID';

CREATE TABLE "TASK_PROCESS_STATUS" (
	"TPS_ID"	CHAR(6)		NOT NULL,
	"TPS_NAME"	VARCHAR(20)		NOT NULL,
	"TPS_ING"	VARCHAR2(20)		NOT NULL,
	"TPS_DESC"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "TASK_PROCESS_STATUS"."TPS_ID" IS '일감처리ID';

COMMENT ON COLUMN "TASK_PROCESS_STATUS"."TPS_NAME" IS '일감처리명';

COMMENT ON COLUMN "TASK_PROCESS_STATUS"."TPS_ING" IS '일감처리 진행률';

COMMENT ON COLUMN "TASK_PROCESS_STATUS"."TPS_DESC" IS '일감처리 설명';

CREATE TABLE "CHAT" (
	"CHAT_ID"	VARCHAR2(100)		NOT NULL,
	"CR_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL,
	"CHAT_CN"	CLOB		NOT NULL,
	"CHAT_REG_DT"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL
);

COMMENT ON COLUMN "CHAT"."CHAT_ID" IS '채팅ID';

COMMENT ON COLUMN "CHAT"."CR_ID" IS '채팅방ID';

COMMENT ON COLUMN "CHAT"."EMP_ID" IS '사원ID';

COMMENT ON COLUMN "CHAT"."CHAT_CN" IS '채팅 내용';

COMMENT ON COLUMN "CHAT"."CHAT_REG_DT" IS '채팅 작성일';

CREATE TABLE "CHAT_ROOM" (
	"CR_ID"	CHAR(6)		NOT NULL,
	"CR_NAME"	VARCHAR2(100)		NOT NULL,
	"CR_GUBUN"	CHAR(6)		NULL,
	"CR_KEY"	VARCHAR2(300)		NULL,
	"CR_DEL_YN"	CHAR(1)		NULL
);

CREATE TABLE "RESOURCE" (
	"RESC_ID"	CHAR(6)		NOT NULL,
	"RESC_NAME"	VARCHAR(30)		NOT NULL,
	"RESC_URL"	VARCHAR2(100)		NOT NULL,
	"RESC_DESC"	CLOB		NULL,
	"RESC_YN"	CHAR(1)		NULL
);

COMMENT ON COLUMN "RESOURCE"."RESC_ID" IS '자원ID';

COMMENT ON COLUMN "RESOURCE"."RESC_NAME" IS '자원명';

COMMENT ON COLUMN "RESOURCE"."RESC_URL" IS '요청메소드';

COMMENT ON COLUMN "RESOURCE"."RESC_DESC" IS '자원 설명';

COMMENT ON COLUMN "RESOURCE"."RESC_YN" IS '자원사용여부';

CREATE TABLE "ROLE_RESOURCE" (
	"RESC_ID"	CHAR(6)		NOT NULL,
	"ROLE_ID"	CHAR(6)		NOT NULL
);

COMMENT ON COLUMN "ROLE_RESOURCE"."RESC_ID" IS '자원ID';

COMMENT ON COLUMN "ROLE_RESOURCE"."ROLE_ID" IS '역할 ID';

CREATE TABLE "MAIL" (
	"EMP_ID"	CHAR(6)		NOT NULL,
	"EXPIRATION_TIME_MILLISECONDS"	CHAR(100)		NOT NULL,
	"ACCES_TOKEN"	VARCHAR2(300)		NULL,
	"REFRESH_TOKEN"	VARCHAR2(300)		NULL
);

COMMENT ON COLUMN "MAIL"."EMP_ID" IS '사원ID';

COMMENT ON COLUMN "MAIL"."EXPIRATION_TIME_MILLISECONDS" IS '만료시간';

COMMENT ON COLUMN "MAIL"."ACCES_TOKEN" IS 'ACCESS토큰';

COMMENT ON COLUMN "MAIL"."REFRESH_TOKEN" IS 'REFRESH토큰';

CREATE TABLE "POSITION" (
	"PS_ID"	CHAR(6)		NOT NULL,
	"PS_NAME"	VARCHAR2(60)		NOT NULL,
	"PS_YN"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "POSITION"."PS_ID" IS '직급ID';

COMMENT ON COLUMN "POSITION"."PS_NAME" IS '직급명';

COMMENT ON COLUMN "POSITION"."PS_YN" IS '직급 사용여부';

CREATE TABLE "CHAT_USER" (
	"CR_ID"	CHAR(6)		NOT NULL,
	"EMP_ID"	CHAR(6)		NOT NULL
);

COMMENT ON COLUMN "CHAT_USER"."CR_ID" IS '채팅방ID';

COMMENT ON COLUMN "CHAT_USER"."EMP_ID" IS '사원ID';

CREATE TABLE "COMMON" (
	"CM_ID"	CHAR(6)		NOT NULL,
	"CM_NAME"	VARCHAR2(100)		NOT NULL,
	"CM_ATT1"	VARCHAR2(100)		NULL,
	"CM_ATT2"	VARCHAR2(100)		NULL,
	"CM_ATT3"	VARCHAR2(100)		NULL,
	"CM_ATT4"	VARCHAR2(100)		NULL,
	"CM_DESC"	CLOB		NULL
);

COMMENT ON COLUMN "COMMON"."CM_ID" IS '공통ID';

COMMENT ON COLUMN "COMMON"."CM_NAME" IS '이름';

COMMENT ON COLUMN "COMMON"."CM_ATT1" IS '속성1';

COMMENT ON COLUMN "COMMON"."CM_ATT2" IS '속성2';

COMMENT ON COLUMN "COMMON"."CM_ATT3" IS '속성3';

COMMENT ON COLUMN "COMMON"."CM_ATT4" IS '속성4';

COMMENT ON COLUMN "COMMON"."CM_DESC" IS '설명';

ALTER TABLE "EMP" ADD CONSTRAINT "PK_EMP" PRIMARY KEY (
	"EMP_ID"
);

ALTER TABLE "ROLE" ADD CONSTRAINT "PK_ROLE" PRIMARY KEY (
	"ROLE_ID"
);

ALTER TABLE "BOOKMARK_BOARD" ADD CONSTRAINT "PK_BOOKMARK_BOARD" PRIMARY KEY (
	"BB_ID"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY (
	"PRO_ID"
);

ALTER TABLE "ISSUE" ADD CONSTRAINT "PK_ISSUE" PRIMARY KEY (
	"ISSUE_ID"
);

ALTER TABLE "FILE_SAVE_FILE" ADD CONSTRAINT "PK_FILE_SAVE_FILE" PRIMARY KEY (
	"FSF_ID"
);

ALTER TABLE "ISSUE_FILE" ADD CONSTRAINT "PK_ISSUE_FILE" PRIMARY KEY (
	"ISSFF_ID"
);

ALTER TABLE "FILE_SAVE_NOTICE" ADD CONSTRAINT "PK_FILE_SAVE_NOTICE" PRIMARY KEY (
	"FSN_ID"
);

ALTER TABLE "TASK" ADD CONSTRAINT "PK_TASK" PRIMARY KEY (
	"TASK_ID"
);

ALTER TABLE "TASK_FILE" ADD CONSTRAINT "PK_TASK_FILE" PRIMARY KEY (
	"TF_ID"
);

ALTER TABLE "TASK_PEP" ADD CONSTRAINT "PK_TASK_PEP" PRIMARY KEY (
	"TP_ID"
);

ALTER TABLE "TODAY_LIST" ADD CONSTRAINT "PK_TODAY_LIST" PRIMARY KEY (
	"TL_REG_DT",
	"TL_IDX"
);

ALTER TABLE "BOARD_POST" ADD CONSTRAINT "PK_BOARD_POST" PRIMARY KEY (
	"BP_ID"
);

ALTER TABLE "BOAD_POST_FILE" ADD CONSTRAINT "PK_BOAD_POST_FILE" PRIMARY KEY (
	"BP_FILE_ID"
);

ALTER TABLE "LIKEE" ADD CONSTRAINT "PK_LIKEE" PRIMARY KEY (
	"EMP_ID",
	"BP_ID"
);

ALTER TABLE "WIKI" ADD CONSTRAINT "PK_WIKI" PRIMARY KEY (
	"WIKI_ID"
);

ALTER TABLE "WIKI_FILE" ADD CONSTRAINT "PK_WIKI_FILE" PRIMARY KEY (
	"WF_ID"
);

ALTER TABLE "ISSUE_COMMENT" ADD CONSTRAINT "PK_ISSUE_COMMENT" PRIMARY KEY (
	"IC_ID"
);

ALTER TABLE "DEPT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY (
	"DEPT_ID"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "PK_BOARD_COMMENT" PRIMARY KEY (
	"BC_ID"
);

ALTER TABLE "ALARM" ADD CONSTRAINT "PK_ALARM" PRIMARY KEY (
	"ALARM_ID"
);

ALTER TABLE "ALARM_TYPE" ADD CONSTRAINT "PK_ALARM_TYPE" PRIMARY KEY (
	"ALTYPE_ID"
);

ALTER TABLE "TEAM" ADD CONSTRAINT "PK_TEAM" PRIMARY KEY (
	"PRO_ID",
	"EMP_ID"
);

ALTER TABLE "TASK_STATUS" ADD CONSTRAINT "PK_TASK_STATUS" PRIMARY KEY (
	"TS_ID"
);

ALTER TABLE "BOOKMARK_ISSUE" ADD CONSTRAINT "PK_BOOKMARK_ISSUE" PRIMARY KEY (
	"BI_ID"
);

ALTER TABLE "FILE_SAVE" ADD CONSTRAINT "PK_FILE_SAVE" PRIMARY KEY (
	"FS_ID"
);

ALTER TABLE "TASK_PROCESS_STATUS" ADD CONSTRAINT "PK_TASK_PROCESS_STATUS" PRIMARY KEY (
	"TPS_ID"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "PK_CHAT" PRIMARY KEY (
	"CHAT_ID"
);

ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "PK_CHAT_ROOM" PRIMARY KEY (
	"CR_ID"
);

ALTER TABLE "RESOURCE" ADD CONSTRAINT "PK_RESOURCE" PRIMARY KEY (
	"RESC_ID"
);

ALTER TABLE "ROLE_RESOURCE" ADD CONSTRAINT "PK_ROLE_RESOURCE" PRIMARY KEY (
	"RESC_ID",
	"ROLE_ID"
);

ALTER TABLE "MAIL" ADD CONSTRAINT "PK_MAIL" PRIMARY KEY (
	"EMP_ID"
);

ALTER TABLE "POSITION" ADD CONSTRAINT "PK_POSITION" PRIMARY KEY (
	"PS_ID"
);

ALTER TABLE "CHAT_USER" ADD CONSTRAINT "PK_CHAT_USER" PRIMARY KEY (
	"CR_ID",
	"EMP_ID"
);

ALTER TABLE "LIKEE" ADD CONSTRAINT "FK_EMP_TO_LIKEE_1" FOREIGN KEY (
	"EMP_ID"
)
REFERENCES "EMP" (
	"EMP_ID"
);

ALTER TABLE "LIKEE" ADD CONSTRAINT "FK_BOARD_POST_TO_LIKEE_1" FOREIGN KEY (
	"BP_ID"
)
REFERENCES "BOARD_POST" (
	"BP_ID"
);

ALTER TABLE "TEAM" ADD CONSTRAINT "FK_PROJECT_TO_TEAM_1" FOREIGN KEY (
	"PRO_ID"
)
REFERENCES "PROJECT" (
	"PRO_ID"
);

ALTER TABLE "TEAM" ADD CONSTRAINT "FK_EMP_TO_TEAM_1" FOREIGN KEY (
	"EMP_ID"
)
REFERENCES "EMP" (
	"EMP_ID"
);

ALTER TABLE "ROLE_RESOURCE" ADD CONSTRAINT "FK_RESOURCE_TO_ROLE_RESOURCE_1" FOREIGN KEY (
	"RESC_ID"
)
REFERENCES "RESOURCE" (
	"RESC_ID"
);

ALTER TABLE "ROLE_RESOURCE" ADD CONSTRAINT "FK_ROLE_TO_ROLE_RESOURCE_1" FOREIGN KEY (
	"ROLE_ID"
)
REFERENCES "ROLE" (
	"ROLE_ID"
);

ALTER TABLE "MAIL" ADD CONSTRAINT "FK_EMP_TO_MAIL_1" FOREIGN KEY (
	"EMP_ID"
)
REFERENCES "EMP" (
	"EMP_ID"
);

ALTER TABLE "CHAT_USER" ADD CONSTRAINT "FK_CHAT_ROOM_TO_CHAT_USER_1" FOREIGN KEY (
	"CR_ID"
)
REFERENCES "CHAT_ROOM" (
	"CR_ID"
);

ALTER TABLE "CHAT_USER" ADD CONSTRAINT "FK_EMP_TO_CHAT_USER_1" FOREIGN KEY (
	"EMP_ID"
)
REFERENCES "EMP" (
	"EMP_ID"
);