#oracle raw driver
#dirverClassName=oracle.jdbc.driver.OracleDriver
#url=jdbc:oracle:thin:@localhost:1521/XE

#=======================================================================

#log4jdbc \uc5d0 \ub9de\uac8c \ubcc0\uacbd
driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
url=jdbc:log4jdbc:oracle:thin:@localhost:1521/XE
user=PC08_03
password=java

#======================================================================= \ud655\uc7a5\uc790\uac00 \uc790\ubc14\uac00\uc774\uae30 \ub54c\ubb38\uc5d0 \uc5b8\uc81c\ub4e0\uc9c0 \uc218\uc815\uac00\ub2a5, 
#connection pooling policy
initialSize=2
maxIdle=2
maxTotal=3
maxWait=2000
